import {BadRequestException,Body,ConflictException,Controller,Injectable,Module,Post,UnauthorizedException} from '@nestjs/common';
import {ConfigService} from '@nestjs/config'; import {JwtService} from '@nestjs/jwt'; import * as bcrypt from 'bcryptjs'; import {createHash,randomBytes,randomUUID} from 'crypto'; import {PrismaService} from './prisma.service';
import {RegisterDto,LoginDto,RefreshTokenDto} from './dto';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
@Injectable() export class AuthService { constructor(private db:PrismaService,private jwt:JwtService,private cfg:ConfigService){} private access(u:any){const mins=Number(this.cfg.get('JWT_DURATION_MINUTES')??15), exp=new Date(Date.now()+mins*60000); return {token:this.jwt.sign({sub:String(u.id),name:u.name,email:u.email,role:u.role,TokenVersion:String(u.tokenVersion)}),exp};} private async result(u:any,family?:string){const a=this.access(u), raw=randomBytes(64).toString('base64url'), exp=new Date(Date.now()+7*86400000); await this.db.refreshToken.create({data:{tokenHash:hash(raw),familyId:family??randomUUID(),userId:u.id,createdAt:new Date(),expiresAt:exp}}); return {userId:u.id,name:u.name,email:u.email,role:u.role,accessToken:a.token,refreshToken:raw,accessTokenExpiresAt:a.exp,refreshTokenExpiresAt:exp,revokedAt:null};}
 async register(d:any){const email=d.email.trim().toLowerCase(); try{return await this.db.$transaction(async tx=>{if(await tx.user.findUnique({where:{email}})) throw new ConflictException('Email is already registered.'); const u=await tx.user.create({data:{name:d.name.trim(),email,hashPassword:await bcrypt.hash(d.password,11),role:'User',tokenVersion:1}}); const a=this.access(u),raw=randomBytes(64).toString('base64url'),exp=new Date(Date.now()+7*86400000); await tx.refreshToken.create({data:{tokenHash:hash(raw),familyId:randomUUID(),userId:u.id,createdAt:new Date(),expiresAt:exp}}); return {userId:u.id,name:u.name,email:u.email,role:u.role,accessToken:a.token,refreshToken:raw,accessTokenExpiresAt:a.exp,refreshTokenExpiresAt:exp,revokedAt:null};},{isolationLevel:'ReadCommitted'});}catch(e){if(e instanceof ConflictException)throw e; return null;}}
 async login(d:any){const u=await this.db.user.findUnique({where:{email:d.email.trim().toLowerCase()}}); if(!u||!(await bcrypt.compare(d.password,u.hashPassword)))return null; return this.result(u);}
 async refresh(raw:string){if(!raw?.trim())return null; return this.db.$transaction(async tx=>{const t=await tx.refreshToken.findUnique({where:{tokenHash:hash(raw)}}); if(!t)return null; if(t.revokedAt){await tx.refreshToken.updateMany({where:{familyId:t.familyId},data:{revokedAt:new Date()}});return null;} if(t.expiresAt<=new Date())return null; const u=await tx.user.findUnique({where:{id:t.userId}});if(!u)return null; await tx.refreshToken.update({where:{id:t.id},data:{revokedAt:new Date()}}); const a=this.access(u),next=randomBytes(64).toString('base64url'),exp=new Date(Date.now()+7*86400000); await tx.refreshToken.create({data:{tokenHash:hash(next),familyId:t.familyId,userId:u.id,createdAt:new Date(),expiresAt:exp}}); return {userId:u.id,name:u.name,email:u.email,role:u.role,accessToken:a.token,refreshToken:next,accessTokenExpiresAt:a.exp,refreshTokenExpiresAt:exp,revokedAt:null};},{isolationLevel:'Serializable'});}
 async logout(raw:string){if(!raw?.trim())return false; return this.db.$transaction(async tx=>{const t=await tx.refreshToken.findUnique({where:{tokenHash:hash(raw)}});if(!t)return false;if(t.revokedAt){await tx.refreshToken.updateMany({where:{familyId:t.familyId},data:{revokedAt:new Date()}});return false;}const u=await tx.user.findUnique({where:{id:t.userId}});if(!u)return false;await tx.refreshToken.update({where:{id:t.id},data:{revokedAt:new Date()}});await tx.user.update({where:{id:u.id},data:{tokenVersion:{increment:1}}});return true;},{isolationLevel:'Serializable'});}}
@Controller('api/Auth') export class AuthController {constructor(private s:AuthService){} @Post('register') async register(@Body()d:RegisterDto){return this.s.register(d)} @Post('login') async login(@Body()d:LoginDto){const r=await this.s.login(d);if(!r)throw new UnauthorizedException({message:'Invalid email or password.'});return r} @Post('refresh') async refresh(@Body()d:RefreshTokenDto){const r=await this.s.refresh(d.refreshToken);if(!r)throw new UnauthorizedException('Invalid refresh token.');return r} @Post('logout') async logout(@Body()d:RefreshTokenDto){if(!await this.s.logout(d.refreshToken))throw new BadRequestException({message:'Invalid or already revoked refresh token.'});return {message:'Logged out successfully.'}}}
@Module({controllers:[AuthController],providers:[PrismaService,AuthService],exports:[AuthService]}) export class AuthModule{}
